name: Main

on: push

jobs:
  build:
    env:
      TARBALL: "./relayd-${{ github.ref_name }}.tar.gz"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3
      - name: Package
        run:  ./release-relayd.sh "${{ github.ref_name }}"
      - name: Test
        run: tar -t -f "${{ env.TARBALL }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.TARBALL }}
