name: Test

on: [push]

permissions:
    contents: read

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        freebsd_version: [13.2]
        os: [macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Run tests"
        uses: vmactions/freebsd-vm@v0
        with:
          release: ${{ matrix.freebsd_version }}
          prepare: |
            pkg install -y libressl
          run: |
            ./configure && make
